package chat

import (
	"testing"

	"github.com/cloudwego/eino/schema"

	"github.com/lufengbai68-gif/my_agent/internal/session"
)

func TestExtractMediaFromSession_Nil(t *testing.T) {
	if got := ExtractMediaFromSession(nil); got != nil {
		t.Errorf("nil session should return nil, got %v", got)
	}
}

func TestExtractMediaFromSession_NoToolMessages(t *testing.T) {
	sess := &session.Session{
		Messages: []*schema.Message{
			schema.UserMessage("hi"),
			schema.AssistantMessage("hello", nil),
		},
	}
	if got := ExtractMediaFromSession(sess); got != nil {
		t.Errorf("no tool messages, should return nil, got %v", got)
	}
}

func TestExtractMediaFromSession_ExtractsMultiple(t *testing.T) {
	sess := &session.Session{
		Messages: []*schema.Message{
			schema.UserMessage("画一只猫"),
			{ // tool 输出 1:图片
				Role:    schema.Tool,
				Content: `{"urls":["https://x/a.png"],"kind":"image","model":"seedream"}`,
			},
			schema.AssistantMessage("给你画好了", nil),
			{ // tool 输出 2:视频
				Role:    schema.Tool,
				Content: `{"urls":["https://x/b.mp4"],"kind":"video","model":"seedance_pro"}`,
			},
			{ // 解析失败的 tool 消息,应跳过
				Role:    schema.Tool,
				Content: "not json",
			},
		},
	}
	got := ExtractMediaFromSession(sess)
	if len(got) != 2 {
		t.Fatalf("want 2 media items, got %d (%+v)", len(got), got)
	}
	if got[0].Type != "image" || got[0].URL != "https://x/a.png" {
		t.Errorf("first: %+v", got[0])
	}
	if got[1].Type != "video" || got[1].URL != "https://x/b.mp4" {
		t.Errorf("second: %+v", got[1])
	}
	if got[0].Description != "Generated by seedream" {
		t.Errorf("description: %q", got[0].Description)
	}
}
