package chat

import (
	"encoding/json"

	"github.com/cloudwego/eino/schema"

	"github.com/lufengbai68-gif/my_agent/internal/session"
)

// MediaItem 一次 chat 回复里携带的多模态产物（图片/视频/音频）。
//
// 由 chat.Service 在工具调用结束后从 tool 输出 JSON 中提取并汇总，
// 作为独立字段发给前端，不再依赖 LLM 是否在文本中正确抄写 URL。
type MediaItem struct {
	// Type image | video | audio
	Type string `json:"type"`
	URL  string `json:"url"`
	// UploadID 是生成产物回传到自有对象存储后的记录 ID。
	// 历史回显时依赖它刷新签名 URL，避免上游临时 URL 过期。
	UploadID string `json:"upload_id,omitempty"`
	// Description 可选：上下文描述（如模型名、用户输入）
	Description string `json:"description,omitempty"`
}

// ExtractMediaFromSession 扫描 session 所有消息,从 Tool 角色 JSON 里抽出 media 列表。
//
// 调用方负责把结果序列化为响应字段;顺序按消息时间线(老→新)。
// 解析失败的消息被静默跳过(与 chat.Service.Complete/Stream 行为一致)。
func ExtractMediaFromSession(sess *session.Session) []MediaItem {
	if sess == nil {
		return nil
	}
	var out []MediaItem
	for _, m := range sess.Messages {
		if m == nil || m.Role != schema.Tool {
			continue
		}
		var got struct {
			URLs  []string `json:"urls"`
			Kind  string   `json:"kind"`
			Model string   `json:"model"`
		}
		if err := json.Unmarshal([]byte(m.Content), &got); err != nil {
			continue
		}
		for _, u := range got.URLs {
			out = append(out, MediaItem{
				Type:        got.Kind,
				URL:         u,
				Description: "Generated by " + got.Model,
			})
		}
	}
	return out
}
